language: objective-c
os: osx
osx_image: xcode10

env:
  global:
    - MAKEFLAGS="-j6"

git:
  submodules: false
  depth: false

branches:
  only:
  - develop

deploy:
  provider: releases
  api_key: $TOKEN
  file: "Undecimus.ipa"
  skip_cleanup: true
  on:
    tags: true

before_install:
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - git submodule update --init
  - brew install dpkg ldid

script: make
